"""How good is each generated world, measured rather than eyeballed.

The 3DGS trainer holds views out of training and scores itself on them, writing
gs_result/stats/val_step<N>.json beside the world. This reads those back for every
splat in a project, so two can be compared without opening two flow runs — and so
a world that came out badly is a line in a table rather than something you notice
weeks later while walking through it.

    python scripts/splat_quality.py <project-dir> [--renders]

What the numbers mean, and what to distrust:

  PSNR   dB against held-out views. Above ~25 is sharp, below ~20 reads soft or
         smeared. It says the splat matches the views it was TRAINED to predict —
         all of which HY-World generated from one photograph. So it measures
         self-consistency, not fidelity to the real room. A world can score well
         and still have invented a corridor.
  SSIM   structural agreement, 0-1. Falls faster than PSNR when geometry is wrong
         rather than merely blurry, so a low SSIM beside a fair PSNR usually means
         the shapes moved, not that the image is noisy.
  LPIPS  perceptual distance, lower better. Closest of the three to "does it look
         right to a person", and the one to trust when PSNR and SSIM disagree.

The renders are the real check: gs_result/renders/val_*.png are the held-out views
side by side, rendered against truth. --renders prints their paths.
"""

import json
import sys
from pathlib import Path

# Below these a world is worth looking at before building on it. Chosen from this
# building's own spread rather than from the literature: sixteen worlds off the
# same pipeline and camera land in a narrow band, so an outlier means something
# happened here, not that the scene was intrinsically hard.
LOW_PSNR = 20.0
LOW_SSIM = 0.78
HIGH_LPIPS = 0.28


def val_stats(splat: Path) -> dict | None:
    """The last validation the trainer ran on this world, or None."""
    stats = sorted((splat / "gs_result" / "stats").glob("val_step*.json"))
    if not stats:
        return None
    try:
        return json.loads(stats[-1].read_text())
    except (OSError, ValueError):
        return None


def report(project_dir: Path, show_renders: bool = False) -> int:
    splats = sorted(p.parent for p in project_dir.glob("splats/*/world.ply"))
    if not splats:
        print(f"no built splats in {project_dir}", file=sys.stderr)
        return 1

    rows = []
    for splat in splats:
        s = val_stats(splat)
        rows.append((splat, s))

    width = max(len(p.name) for p, _ in rows)
    print(f"  {'world':{width}}  {'PSNR':>6} {'SSIM':>6} {'LPIPS':>6} {'gaussians':>10}")
    scored = []
    for splat, s in sorted(rows, key=lambda r: -(r[1] or {}).get("psnr", 0)):
        if not s:
            print(f"  {splat.name:{width}}  {'— not scored (training left no val stats)':>6}")
            continue
        flags = []
        if s["psnr"] < LOW_PSNR:
            flags.append("soft")
        if s.get("ssim", 1) < LOW_SSIM:
            flags.append("geometry")
        if s.get("lpips", 0) > HIGH_LPIPS:
            flags.append("looks wrong")
        scored.append(s["psnr"])
        print(f"  {splat.name:{width}}  {s['psnr']:>6.2f} {s.get('ssim', 0):>6.3f} "
              f"{s.get('lpips', 0):>6.3f} {int(s.get('num_GS', 0)):>10,}"
              + (f"   ({', '.join(flags)})" if flags else ""))
        if show_renders:
            for png in sorted((splat / "gs_result" / "renders").glob("val_*.png"))[:3]:
                print(f"      {png}")

    if scored:
        scored.sort()
        mid = scored[len(scored) // 2]
        print(f"\n  {len(scored)} scored · median PSNR {mid:.2f} · "
              f"range {scored[0]:.2f}–{scored[-1]:.2f}")
    print("\n  Held-out views, so this is self-consistency: every one of them was\n"
          "  generated by HY-World from a single photograph. A world can score well\n"
          "  and still have invented a corridor — the renders under\n"
          "  gs_result/renders/ are the check that catches that (--renders).")
    return 0


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    sys.exit(report(Path(args[0]), "--renders" in sys.argv))
